#!/bin/sh

# Use timeout to kill any process running longer than 10 minutes.
#BH timeout -k 2m 10m /usr/local/bin/update-bug change-merged "$@"
#BH timeout -k 2m 10m /usr/local/bin/notify-impact change-merged "$@" --impact DocImpact --dest-address 'openstack-docs@lists.elasticdb.org' --config /home/gerrit2/review_site/hooks/notify_impact.yaml
