---
- hosts: review.elasticdb.org
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
- hosts: zuul.elasticdb.org
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
- hosts: jenkins01.elasticdb.org
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
- hosts: ci-puppetmaster.openstacklocal
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
- hosts: cacti.elasticdb.org
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
- hosts: ci-backup-01.elasticdb.org
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
- hosts: puppetdb.elasticdb.org
  gather_facts: false
  max_fail_percentage: 100
  roles:
    - { role: puppet, puppetmaster: ci-puppetmaster.openstacklocal }
